"""ChatGPT2API Manifest。"""

from __future__ import annotations

from app.worker.plugins.manifest import Manifest

DEFAULT_STYLE_TEMPLATES = """写实=请以高质量写实摄影风格生成：{prompt}
海报=请以精致商业海报风格生成，构图清晰，文字区域干净：{prompt}
头像=请生成适合作为头像的正方形主体构图，背景简洁：{prompt}
二次元=请以精致二次元插画风格生成：{prompt}
Logo=请生成简洁现代的品牌 Logo 草案，适合矢量化：{prompt}"""

DEFAULT_MESSAGE_TEMPLATE = """<b>ChatGPT2API</b>
<b>状态:</b> {status}
<b>提示词:</b> {prompt}
<b>模型:</b> {model} · <b>数量:</b> {count}
<b>画幅:</b> {size} · <b>格式:</b> {image_format}
<b>耗时:</b> {elapsed}"""

MANIFEST = Manifest(
    key="chatgpt_image",
    display_name="ChatGPT2API",
    version="0.1.0",
    author="builtin",
    description="实验性：按 chatgpt2api 的核心思路在 Telegram 内完成 ChatGPT 图片生成、编辑与 token 池管理。",
    category="utility",
    experimental=True,
    permissions=["send_message", "edit_message", "read_chat", "send_file"],
    config_schema={
        "type": "object",
        "x-ui-mode": "single",
        "additionalProperties": False,
        "properties": {
            "command": {
                "type": "string",
                "title": "文生图命令",
                "description": "Telegram 中触发文生图的命令名，不含系统前缀。例：draw；实际使用为 ,draw 提示词。",
                "default": "draw",
                "minLength": 1,
                "maxLength": 32,
                "pattern": "^\\S+$",
                "level": "account",
            },
            "edit_command": {
                "type": "string",
                "title": "图片编辑命令",
                "description": "回复图片后触发图片编辑的命令名，不含系统前缀。例：edit；也支持 ,edit last 续改最近图片。",
                "default": "edit",
                "minLength": 1,
                "maxLength": 32,
                "pattern": "^\\S+$",
                "level": "account",
            },
            "admin_command": {
                "type": "string",
                "title": "管理命令",
                "description": "查看模型、token 池、刷新额度、导入账号和测试代理的管理命令名。例：gptimg。",
                "default": "gptimg",
                "minLength": 1,
                "maxLength": 32,
                "pattern": "^\\S+$",
                "level": "account",
            },
            "token": {
                "type": "string",
                "title": "旧版 Token 池",
                "description": "兼容旧版多行 token 配置。新配置页会自动迁移到下方结构化 token 池，一条 token 可带一个备注。",
                "default": "",
                "x-ui-widget": "textarea",
                "level": "account",
            },
            "tokens": {
                "type": "array",
                "title": "ChatGPT Token 池",
                "description": "一条一条保存 ChatGPT access token；每条可填写备注，用来标记 token 来源。页面会以首尾各 10 字符脱敏显示。",
                "default": [],
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "token": {
                            "type": "string",
                            "title": "Access Token",
                            "description": "ChatGPT access token。支持从 chatgpt.com/api/auth/session 的 JSON 中自动提取 accessToken。",
                        },
                        "note": {
                            "type": "string",
                            "title": "备注",
                            "description": "这条 token 的来源说明，例如账号邮箱、sub2api 分组或 CPA 文件名。",
                            "default": "",
                        },
                    },
                    "required": ["token"],
                },
                "level": "account",
            },
            "default_model": {
                "type": "string",
                "title": "默认图片模型",
                "description": "未在命令中用 -m 指定模型时使用。gpt-image-2 走官网图片链路；codex-gpt-image-2 走 Codex 图片链路。",
                "default": "gpt-image-2",
                "enum": [
                    "gpt-image-2",
                    "codex-gpt-image-2",
                    "auto",
                    "gpt-5",
                    "gpt-5-1",
                    "gpt-5-2",
                    "gpt-5-3",
                    "gpt-5-3-mini",
                    "gpt-5-mini",
                ],
                "level": "account",
            },
            "available_models": {
                "type": "string",
                "title": "可选模型列表",
                "description": "每行一个模型名。管理命令 models 会展示这里的列表，命令参数 -m 也会按这里校验；留空时使用内置默认列表。",
                "default": "gpt-image-2\ncodex-gpt-image-2\nauto\ngpt-5\ngpt-5-1\ngpt-5-2\ngpt-5-3\ngpt-5-3-mini\ngpt-5-mini",
                "x-ui-widget": "textarea",
                "level": "account",
            },
            "default_count": {
                "type": "integer",
                "title": "默认生成张数",
                "description": "未在命令中用 -n 指定数量时默认生成几张图片。",
                "default": 1,
                "minimum": 1,
                "maximum": 4,
                "level": "account",
            },
            "max_count": {
                "type": "integer",
                "title": "单次最多张数",
                "description": "限制一次命令最多生成多少张图片。个人使用建议 1-4。",
                "default": 4,
                "minimum": 1,
                "maximum": 4,
                "level": "account",
            },
            "default_size": {
                "type": "string",
                "title": "默认画幅提示",
                "description": "会追加到提示词中引导构图。可选：auto、1:1、16:9、9:16、4:3、3:4；也可以填写自定义画幅说明。",
                "default": "1:1",
                "level": "account",
            },
            "image_format": {
                "type": "string",
                "title": "发送图片格式",
                "description": "Telegram 发送文件名使用的默认后缀。实际格式仍以 ChatGPT 返回的图片字节为准。",
                "default": "png",
                "enum": ["png", "jpeg", "webp"],
                "level": "account",
            },
            "output_mode": {
                "type": "string",
                "title": "结果发送方式",
                "description": "image 表示按图片发送；file 表示按文件发送；auto 表示优先图片，失败后改发文件。",
                "default": "auto",
                "enum": ["auto", "image", "file"],
                "level": "account",
            },
            "message_template": {
                "type": "string",
                "title": "消息模板",
                "description": "用于最终图片 caption 的输出格式。支持 {status}、{prompt}、{model}、{count}、{size}、{image_format}、{elapsed} 等占位符。",
                "default": DEFAULT_MESSAGE_TEMPLATE,
                "x-ui-widget": "textarea",
                "level": "account",
            },
            "style_templates": {
                "type": "string",
                "title": "风格模板",
                "description": "每行一个模板，格式为 名称=模板内容。模板里用 {prompt} 代表原始提示词。命令可用 -s 名称 选择。",
                "default": DEFAULT_STYLE_TEMPLATES,
                "x-ui-widget": "textarea",
                "level": "account",
            },
            "default_style": {
                "type": "string",
                "title": "默认风格",
                "description": "未在命令中用 -s 指定风格时默认套用的模板名。留空表示不套风格模板。",
                "default": "",
                "level": "account",
            },
            "timeout": {
                "type": "integer",
                "title": "请求超时（秒）",
                "description": "单个 ChatGPT 请求的网络超时时间。图片生成通常较慢，建议 180-300 秒。",
                "default": 300,
                "minimum": 30,
                "maximum": 900,
                "level": "account",
            },
            "poll_timeout": {
                "type": "integer",
                "title": "结果轮询超时（秒）",
                "description": "SSE 结束后若还没有拿到图片，会继续查询会话结果，直到超过此时间。",
                "default": 180,
                "minimum": 30,
                "maximum": 900,
                "level": "account",
            },
            "poll_interval": {
                "type": "integer",
                "title": "结果轮询间隔（秒）",
                "description": "查询会话图片结果的间隔。过短可能触发上游限流，建议 5-15 秒。",
                "default": 10,
                "minimum": 3,
                "maximum": 60,
                "level": "account",
            },
            "remember_last_image": {
                "type": "boolean",
                "title": "记住最近图片",
                "description": "开启后可使用 edit last 续改最近一次生成或编辑得到的图片。此记录只保存在 worker 内存中，重启后会丢失。",
                "default": True,
                "level": "account",
            },
            "reference_image_limit": {
                "type": "integer",
                "title": "最多参考图数量",
                "description": "图片编辑时最多读取多少张参考图。回复相册时会自动收集同组图片。",
                "default": 6,
                "minimum": 1,
                "maximum": 10,
                "level": "account",
            },
            "skip_failed_seconds": {
                "type": "integer",
                "title": "失败 token 跳过秒数",
                "description": "某个 token 出现鉴权、额度或网络错误后，临时跳过这段时间，再重新参与轮询。",
                "default": 600,
                "minimum": 0,
                "maximum": 86400,
                "level": "account",
            },
            "auto_disable_invalid_tokens": {
                "type": "boolean",
                "title": "自动禁用失效 token",
                "description": "开启后，检测到 token 已失效时会在内存中标记为异常并跳过；配置原文不会被自动删除。",
                "default": True,
                "level": "account",
            },
            "health_check_enabled": {
                "type": "boolean",
                "title": "启用健康检测",
                "description": "定时刷新 token 额度与代理可用性，并把结果写入插件日志。",
                "default": False,
                "level": "account",
            },
            "health_check_interval": {
                "type": "integer",
                "title": "健康检测间隔（秒）",
                "description": "健康检测的执行间隔。仅在启用健康检测后生效。",
                "default": 3600,
                "minimum": 300,
                "maximum": 86400,
                "level": "account",
            },
            "sub2api_base_url": {
                "type": "string",
                "title": "sub2api 地址",
                "description": "sub2api 管理端地址。用于 gptimg import sub2api 拉取 OpenAI OAuth 账号。",
                "default": "",
                "level": "account",
            },
            "sub2api_email": {
                "type": "string",
                "title": "sub2api 邮箱",
                "description": "sub2api 登录邮箱。若已填写 API Key，可留空。",
                "default": "",
                "level": "account",
            },
            "sub2api_password": {
                "type": "string",
                "title": "sub2api 密码",
                "description": "sub2api 登录密码。若已填写 API Key，可留空。",
                "default": "",
                "level": "account",
            },
            "sub2api_api_key": {
                "type": "string",
                "title": "sub2api API Key",
                "description": "sub2api 管理 API Key。填写后优先用它访问，无需邮箱密码。",
                "default": "",
                "level": "account",
            },
            "sub2api_group_id": {
                "type": "string",
                "title": "sub2api 分组 ID",
                "description": "只导入指定分组的账号。留空表示读取所有 OpenAI OAuth 账号。",
                "default": "",
                "level": "account",
            },
            "cpa_base_url": {
                "type": "string",
                "title": "CPA 地址",
                "description": "CLIProxyAPI 管理端地址。用于 gptimg import cpa 浏览或导入远程 auth 文件。",
                "default": "",
                "level": "account",
            },
            "cpa_secret_key": {
                "type": "string",
                "title": "CPA Secret Key",
                "description": "CPA 管理接口密钥，只用于请求远程 auth 文件，不会写入日志。",
                "default": "",
                "level": "account",
            },
            "cpa_file_names": {
                "type": "string",
                "title": "CPA 文件名",
                "description": "要导入的 CPA auth 文件名，每行一个。留空时 import cpa 只列出远程文件，不导入。",
                "default": "",
                "x-ui-widget": "textarea",
                "level": "account",
            },
            "log_prompt_preview": {
                "type": "boolean",
                "title": "记录提示词摘要",
                "description": "开启后插件日志会记录截断后的提示词摘要，默认不记录完整提示词。",
                "default": True,
                "level": "account",
            },
            "template_placeholders": {
                "type": "string",
                "title": "命令说明",
                "description": "只读说明：所有主命令都可自定义，子命令固定为 ping、models、status、version、refresh、token、import、proxy。",
                "default": "文生图：,{command} [-m 模型] [-n 数量] [-s 风格] [--size 画幅] 提示词\n图片编辑：回复图片后 ,{edit_command} 提示词；或 ,{edit_command} last 提示词\n管理：,{admin_command} ping/models/status/version/refresh/token/import/proxy",
                "readOnly": True,
                "level": "account",
            },
        },
        "required": [
            "command",
            "edit_command",
            "admin_command",
            "default_model",
            "default_count",
            "max_count",
            "timeout",
        ],
    },
)

__all__ = ["MANIFEST"]
